### PR TITLE
PoofV2

### PR DESCRIPTION
**Pull request by kyscott18**
poof cusd v2 and celo v2

### CODE REVIEW

**Review by 0xhuman — APPROVED** [review]
Looks good, assuming we want LP-token names to remain the same (i.e. not say V2)

**Comment by d-mooers** [comment]
Could we rename old poof assets PoofxV1 ? I think that's how they're naked on Ubeswap. I'll try to confirm though

**Comment by kyscott18** [comment]
I updated naming of assets to 'pUSDxV1' and 'pUSD' and naming of pools to 'Poof USD V1' and Poof USD V2'

**Review by d-mooers — APPROVED** [review]
lgtm!

**Pull request merged**
